### ISSUE TITLE
[windows, docker] video tools fail with `OSError: [Errno 18] Invalid cross-device link'

### ISSUE THREAD

**Issue by johnny-smitherson** [Woolverine94/biniou#57]
**Describe the bug**
If multiple hard disks are in use, all video features fail to work when running on Windows (both directly or through docker desktop).

This is caused by [`os.rename()`](https://docs.python.org/3/library/os.html#os.rename): 

> The operation may fail if src and dst are on different filesystems. 

**To Reproduce**
1. Have a bunch of disks connected to Windows - put Docker Desktop on one, the model & output volume on another.
2. Go to 'Video > Stable Video Diffusion'
3. Click on 'Generate'

**Expected behavior**
No error

**Console log**

```
>>>[Stable Video Diffusion 📼 ]: Settings : Model=stabilityai/stable-video-diffusion-img2vid | Sampler=Euler | Steps=15 | Min guidance scale=1 | Max guidance scale=3 | Video length=14 frames | FPS=7 frames | Chunck size=7 | Size=512x512 | Motion bucket id=127 | Noise strength=0.02 | GFPGAN=True | nsfw_filter=True | Seed List=1806261462
Traceback (most recent call last):
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api  
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync     
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper        
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/env/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper        
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/ressources/common.py", line 577, in wrap_func
    result = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/biniou/biniou/ressources/img2vid.py", line 163, in video_img2vid
    metadata_writer_mp4(reporting_img2vid, savename)
  File "/home/biniou/biniou/ressources/common.py", line 696, in metadata_writer_mp4
    os.rename(filename_list[j], ".tmp/tmp.mp4")
OSError: [Errno 18] Invalid cross-device link: 'outputs/1731090542_2888167_1806261462.mp4' -> '.tmp/tmp.mp4'
```

**Additional context**

Unless you have a laptop with a single big SSD in it, the risk of hitting the "different filesystem" error is very high on windows.

All `os.rename()` calls could be changed to [shutil.move()](https://docs.python.org/3/library/shutil.html#shutil.move) as mentioned in above docs.

**Comment by Woolverine94** [comment]
Hello @johnny-smitherson,

Thank you very much for reporting this issue and for providing a workaround for it ! 

I need to do some tests to evaluate the consequences of replacing os.rename by shutil.move, but it shouldn't be an issue, and  I'll try to provide a bugfix for this issue later today. 

On the other hand, I don't have any clue for the other error you encountered while putting .tmp dir on the same drive. Can it be excluded it's some kind of lock on your drive for the ./tmp dir, making the reported error legit ?

**Comment by johnny-smitherson** [comment]
The error is legit - the code is running `shutil.rmtree` on the `.tmp`  dir. 

When `.tmp` is mounted as volume, it cannot be removed from inside the container, as it's now a mount point managed by docker. This is why the `rmtree` command fails.

To allow for such a use, this line
```
  File "/home/biniou/biniou/webui.py", line 32, in <module>
    shutil.rmtree(tmp_biniou)
```

Would need to be changed for a different delete logic that preserves the root `tmp_binou` dir if it exists, such as os.walk() + os.remove()

Another option would be to use the system temp dir (` tempfile.gettempdir() ` - `/tmp` on linux and `C:/...` on windows) instead of this "home folder" location that must reside on the docker image. I can mount `/tmp` as a volume in docker.

**Comment by Woolverine94** [comment]
> The error is legit - the code is running shutil.rmtree on the .tmp dir.
> When .tmp is mounted as volume, it cannot be removed from inside the container, as it's now a mount point managed by docker. This is why the rmtree command fails.

Yeah, I just got it (it's friday night and "Happy hour" has already started here ^^). 

I think that the right approach would be to delete the content of .tmp instead of the whole directory. In fact, this .tmp dir is not a real tmp, but only a convenient (and pretty dirty) way to store generated files that requires a specific processing, but could be deleted after.

I'll' give it a try. 

Thanks again for your reports and advice.

**Comment by Woolverine94** [comment]
Hello again @, 

Commit 1e6f37b address the behaviors you reported. 

It should allow you to:
  - Generate any kind of video contents without error
  - Create a mount point for .tmp

Thanks again for reporting this issue and providing bugfixes for it.

I close this issue as this commit should fix all the errors you encountered, but don't hesitate to re-open it if required.
